name: jobs_flutter_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 3.0.1
  flutter_screenutil: 5.5.4
  cached_network_image: ^3.2.2
  flutter_svg: 1.1.5
  lottie: 1.4.2
  carousel_slider: 4.1.1
  flutter_markdown: 0.6.12
  persistent_bottom_nav_bar_v2: 4.2.5
  dio: 4.0.6
  get_it: 7.2.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  flutter_zoom_drawer: 3.0.3
  intl: 0.17.0
  get_storage: 2.0.3
  heroicons: 0.7.0
  form_field_validator: 1.1.0
  intl_phone_field: 3.1.0
  shimmer: 2.0.0
  awesome_dialog: 3.0.2
  awesome_snackbar_content: 0.0.8
  country_codes: 2.2.0
  smooth_page_indicator: 1.0.0+2
  url_launcher: 6.1.6
  flutter_svg_provider: 1.0.3
  expandable: 5.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  freezed: ^2.1.1
  json_serializable: ^6.4.0
  flutter_native_splash: ^2.2.10+1
  logger: 1.1.0
  device_preview: ^1.1.0
  flutter_test: 
    sdk: flutter

flutter_native_splash: 
  color: '#03A9F4'
  color_dark: '#23A9F4'
  image: assets/logo.png
  image_dark: assets/logo.png
  android_12: 
    image: assets/logo.png
    color_dark: '#23A9F4'
  web: false

flutter: 
  assets: 
    - assets/
  uses-material-design: true

